-- MySQL Script generated by MySQL Workbench
-- Mon Dec  2 10:20:24 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Noticias`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Noticias` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Noticias` (
  `idNoticia` INT NOT NULL,
  `titulo` INT NULL,
  `noticia` VARCHAR(10000) NULL,
  `data_hora_publicacao` DATETIME NULL,
  `data_hora_atualizacao` DATETIME NULL,
  `titulo_imagem_capa` VARCHAR(1000) NULL,
  `autor_imagem_capa` BLOB NULL,
  `imagem_capa` BLOB NULL,
  `num_visualizacoes` INT NULL,
  `classificacao` VARCHAR(100) NULL,
  PRIMARY KEY (`idNoticia`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Autores`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Autores` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Autores` (
  `cpf` INT NOT NULL,
  `nome` VARCHAR(300) NULL,
  PRIMARY KEY (`cpf`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Assinantes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Assinantes` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Assinantes` (
  `cpf` INT NOT NULL,
  `nome` VARCHAR(300) NULL,
  `data_assinatura` DATE NULL,
  `data_vencimento` DATE NULL,
  PRIMARY KEY (`cpf`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Noticias_Autores`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Noticias_Autores` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Noticias_Autores` (
  `fk_idNoticia` INT NOT NULL,
  `fk_cpf` INT NOT NULL,
  PRIMARY KEY (`fk_idNoticia`, `fk_cpf`),
  INDEX `fk_Noticias_Autores_Autores1_idx` (`fk_cpf` ASC) VISIBLE,
  CONSTRAINT `fk_Noticias_Autores_Noticias`
    FOREIGN KEY (`fk_idNoticia`)
    REFERENCES `mydb`.`Noticias` (`idNoticia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Noticias_Autores_Autores1`
    FOREIGN KEY (`fk_cpf`)
    REFERENCES `mydb`.`Autores` (`cpf`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Comentarios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Comentarios` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Comentarios` (
  `comentario` INT NOT NULL,
  `data_publicacao` DATE NULL,
  `hora_publicacao` DATETIME NULL,
  `curtida_positiva` INT NULL,
  `curtida_negativa` INT NULL,
  `Noticias_idNoticia` INT NOT NULL,
  `Assinantes_cpf` INT NOT NULL,
  PRIMARY KEY (`comentario`),
  INDEX `fk_Comentarios_Noticias1_idx` (`Noticias_idNoticia` ASC) VISIBLE,
  INDEX `fk_Comentarios_Assinantes1_idx` (`Assinantes_cpf` ASC) VISIBLE,
  CONSTRAINT `fk_Comentarios_Noticias1`
    FOREIGN KEY (`Noticias_idNoticia`)
    REFERENCES `mydb`.`Noticias` (`idNoticia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Comentarios_Assinantes1`
    FOREIGN KEY (`Assinantes_cpf`)
    REFERENCES `mydb`.`Assinantes` (`cpf`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Controle_Curtidas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Controle_Curtidas` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Controle_Curtidas` (
  `curtida` TINYINT NULL,
  `dataHora` DATETIME NULL,
  `fk_comentario` VARCHAR(500) NOT NULL,
  `fk_cpf` INT NOT NULL,
  PRIMARY KEY (`fk_comentario`, `fk_cpf`),
  INDEX `fk_Controle_Curtidas_Assinantes1_idx` (`fk_cpf` ASC) VISIBLE,
  CONSTRAINT `fk_Controle_Curtidas_Comentarios1`
    FOREIGN KEY (`fk_comentario`)
    REFERENCES `mydb`.`Comentarios` (`comentario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Controle_Curtidas_Assinantes1`
    FOREIGN KEY (`fk_cpf`)
    REFERENCES `mydb`.`Assinantes` (`cpf`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
